TallinnaRakenduslikKolledge_Leib/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TallinnaRakenduslikKolledge_Leib.Data;
using TallinnaRakenduslikKolledge_Leib.Models;

namespace TallinnaRakenduslikKolledge_Leib.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SchoolContext _context;
        public CoursesController(SchoolContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var courses = _context.Courses.Include(c => c.Department).AsNoTracking();
            return View(courses);
        }

        // Create //
        [HttpGet]
        public IActionResult Create() 
        {
            PopulateDepartmentsDropDownList();
            ViewData["ViewType"] = "Create";
            return View("CreateEdit");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            PopulateDepartmentsDropDownList();
            ViewData["ViewType"] = "Edit";
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Courses.FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }
            return View("CreateEdit", course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEdit([Bind("CourseId,Title,Credits,DepartmentId")] Course course, string ViewType)
        {
            if (ModelState.IsValid)
            {
                if (ViewType == "Edit")
                {
                    _context.Update(course);

                }
                else
                {
                    _context.Add(course);
                }
                await _context.SaveChangesAsync();
            }
            if (ViewType == "Edit")
            {
                return View(course);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // Delete //
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["ViewType"] = "Delete";
            if (id == null || _context.Courses == null) 
            {
                return NotFound();
            }
            var courses = await _context.Courses
                .Include(c => c.Department)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (courses == null) 
            {
                return NotFound();
            }
            return View("DeleteDetails", courses);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return NotFound();
            }
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // Details //
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["ViewType"] = "Details";
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Courses.FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }
            return View("DeleteDetails", course);
        }

        // Populate //
        private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
        {
            var departmentQuery = from d in _context.Departments 
                                  orderby d.Name 
                                  select d;
            ViewBag.DepartmentId = new SelectList(departmentQuery.AsNoTracking(), "DepartmentId", "Name", selectedDepartment);
        }

    }
}

TallinnaRakenduslikKolledge_Leib/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TallinnaRakenduslikKolledge_Leib.Data;
using TallinnaRakenduslikKolledge_Leib.Models;

namespace TallinnaRakenduslikKolledge_Leib.Controllers
{
    public class DepartmentsController : Controller
    {

        private readonly SchoolContext _context;
        public DepartmentsController(SchoolContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var SchoolContext = _context.Departments.Include(d => d.Administrator);
            return View(await SchoolContext.ToListAsync());
        }

        // CREATE //
        [HttpGet]
        public IActionResult Create() 
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName");
            ViewData["ViewType"] = "Create";
            //ViewData["CurrentRating"] = new SelectList(_context.Students, "Id", "FirstName", "LastName");
            return View("CreateEdit");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName");
            ViewData["ViewType"] = "Edit";
            if (id == null)
            {
                return NotFound();
            }
            var department = await _context.Departments.FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }
            return View("CreateEdit", department);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEdit([Bind("DepartmentId,Name,Budget,StartDate,RowVersion,InstructorId,CurrentRating")] Department department, string ViewType)
        {
            if (ModelState.IsValid)
            {
                if (ViewType == "Edit")
                {
                    _context.Update(department);

                }
                else
                {
                    _context.Add(department);
                }
                await _context.SaveChangesAsync();
            }
            if (ViewType == "Edit")
            {
                return View(department);
			}
            else
            {
                ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName", department.InstructorId);
                return RedirectToAction("Index");
            }
            //ViewData["CurrentRating"] = new SelectList(_context.Instructors, "Id", department.CurrentRating.ToString(), department.CurrentRating);
        }

        // DELETE //
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName");
            ViewData["ViewType"] = "Delete";
            if (id == null)
            {
                return NotFound();
            }
            var department = await _context.Departments.FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }
            return View("DeleteDetails", department);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName");
            ViewData["ViewType"] = "Details";
            if (id == null)
            {
                return NotFound();
            }
            var department = await _context.Departments.FirstOrDefaultAsync(m => m.DepartmentId == id);
            if (department == null)
            {
                return NotFound();
            }
            return View("DeleteDetails", department);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Department department)
        {
            if (await _context.Departments.AnyAsync(m => m.DepartmentId == department.DepartmentId)) 
            {
                _context.Departments.Remove(department);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

TallinnaRakenduslikKolledge_Leib/Controllers/StudentsController.cs
using System.Linq.Expressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TallinnaRakenduslikKolledge_Leib.Data;
using TallinnaRakenduslikKolledge_Leib.Models;

namespace TallinnaRakenduslikKolledge_Leib.Controllers
{
    public class StudentsController : Controller
    {
        // CONTEXT //
        private readonly SchoolContext _context;
        public StudentsController(SchoolContext context) 
        {
            _context = context;
        }

        // INDEX //
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        // CREATE //
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind
            ("Id,LastName,FirstName,EnrollmentDate,Email")] Student student)
        {
            if (ModelState.IsValid) 
            {
                _context.Students.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index"); // Alternative: "return RedirectToAction(nameof(Index))"

            }
            return View(student);
        }
        
        // DELETE //
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // DETAIL //
        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // EDIT //
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmEdit([Bind
            ("Id,LastName,FirstName,EnrollmentDate,Email")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Students.Update(student);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index"); // Alternative: "return RedirectToAction(nameof(Index))"

            }
            return View(student);
        }
        
        [HttpPost, ActionName("Clone")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Clone([Bind
            ("Id,LastName,FirstName,EnrollmentDate,Email")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Students.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index"); // Alternative: "return RedirectToAction(nameof(Index))"

            }
            return View(student);
        }

    }
}

TallinnaRakenduslikKolledge_Leib/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TallinnaRakenduslikKolledge_Leib</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TallinnaRakenduslikKolledge_Leib.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TallinnaRakenduslikKolledge_Leib</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Avaleht</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Õpilased</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="Index">Õpetajad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Osakonnad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Kursused</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy2">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TallinnaRakenduslikKolledge_Leib - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>